[build]
  command = "npx next build"
  publish = "out"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."stripe-webhook"]
  included_files = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
