[build]
  command = "npx next build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[functions."stripe-webhook"]
  included_files = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
